### ISSUE TITLE
Check whether or not the installation instructions work

### ISSUE THREAD

**Issue by alexraileanu** [alexraileanu/yacms#9]
I wrote the installation instructions (and tested them myself to a certain degree) but I don't know 100% if they work. please test it and make a PR fixing anything I may have missed.

**Comment by markvl** [comment]
Hi Alex,

I was working on this issue and was following the README to see if I could get YaCMS working with them, but it failed on the build step:

```
Step 12/13 : COPY ./config/config.docker.cfg ./config/config.cfg
COPY failed: stat /var/lib/docker/tmp/docker-builder510143818/config/config.docker.cfg: no such file or directory
```
And I can confirm there is no `config/config.docker.cfg` file in the repo. This is something that is more than a documentation change. :)  Is the right config file missing from the repo or should the `Dockerfile` perhaps be changed to copy the `config/config.example.cfg` file?

The next step is also not clear to me:

> After that's done, create a new database and username for the cms ...

It's been a while since I last touched MySQL. Perhaps you have some instructions that could be helpful here?

In that same step:

> ... populate the variable SQLALCHEMY_DATABASE_URI in config/config.cfg accordigly.

I'm not sure what do do here... Should I first copy `config/config.example.cfg` to `config/config.cfg` and edit the `SQLALCHEMY_DATABASE_URI` in that copy? Or should `config/config.cfg` be an empty file with just this URI?  (I can modify the README, I just don't know what you mean here.)

I have created an initial pull request, but I'll update it once I can build the image and have a bit more information. :)

Thanks,
Mark

**Comment by alexraileanu** [comment]
Hey, Mark.

Thanks for taking the time to going thru the README :). I will try to answer your questions.

> And I can confirm there is no config/config.docker.cfg file in the repo. This is something that is more than a documentation change. :) Is the right config file missing from the repo or should the Dockerfile perhaps be changed to copy the config/config.example.cfg file`

You're right, this is some leftovers from when I was trying to do some other stuff. The right file to copy in the Dockerfile is config/config.example.cfg.

> It's been a while since I last touched MySQL. Perhaps you have some instructions that could be helpful here?

Yeah, you can use the following commands to create a user/database combo (feel free to adjust as you wish):

```
create database yacms;
create user '$USER'@'%' identified by '$PASSWORD';
grant all privileges on yacms.* to '$USER'@'%';
flush privileges;
```

Running these 4 statements do the following:

- Creates a database called yacms
- Creates a user with a password (replace $USER and $PASSWORD with your desired values)
- Grants all privileges on the newly created database to this user
- Last one just flushes the privileges table


> I'm not sure what do do here... Should I first copy config/config.example.cfg to config/config.cfg and edit the SQLALCHEMY_DATABASE_URI in that copy? Or should config/config.cfg be an empty file with just this URI? (I can modify the README, I just don't know what you mean here.)

Sorry, I'm really bad at writing instructions haha. What I meant there is to first copy the config.example.cfg to config.cfg and then populate the SQLALCHEY_DATABASE_URI with your values. Following the example above it would be something like this (replace the values according to your setup): 

`SQLALCHEMY_DATABASE_URI = 'mysql://$USER:PASSWORD@localhost:3306/yacms'` 

Please do let me know if you have any additional questions and I'll be more than glad to answer them :).

Alex.

**Comment by markvl** [comment]
Thanks for your fast answers Alex!

With your feedback I was able to get YaCMS running. I have added another commit to my pull request with extra changes to the README to include the steps I had to take.

Hope this helps,
Mark

**Comment by alexraileanu** [comment]
Many thanks! I have merged your PR.

**Comment by markvl** [comment]
You are welcome, it was my pleasure! It really was a fun task to do. :)
